### ISSUE TITLE
Add language support for Swedish and English

### ISSUE THREAD

**Issue by okaziya** [okaziya/cv#5]
See #1 for designs.

**Comment by mkl-adsn** [comment]
@mblomdahl Not a bad idea at all!  Made a quick design for it: https://www.figma.com/proto/m9dxY4C87AiwRn8qyzDHs9/Liza-CV-Site?page-id=0%3A1&node-id=109-1451&node-type=canvas&viewport=3348%2C1683%2C1&t=0XxfEgjtFm1EszSE-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=109%3A1451&show-proto-sidebar=1

**Comment by okaziya** [comment]
Resolved with #9
